const fs = require('fs');
const path = require('path');

const LEADS_FILE = path.join(__dirname, 'processed_leads', 'clean_leads.json');

try {
    const leads = JSON.parse(fs.readFileSync(LEADS_FILE, 'utf8'));
    console.log(`Checking ${leads.length} leads...`);

    // Filter out "Anonymous Mail User" generated by automated emails
    const cleanLeads = leads.filter(l =>
        l.name !== "Anonymous Mail User" &&
        !l.email.includes("no-reply") &&
        !l.email.includes("mailer-daemon")
    );

    if (leads.length !== cleanLeads.length) {
        console.log(`Found ${leads.length - cleanLeads.length} junk leads. Removing...`);
        fs.writeFileSync(LEADS_FILE, JSON.stringify(cleanLeads, null, 2));
        console.log("✅ Cleanup Complete.");
    } else {
        console.log("✅ No junk leads found.");
    }

} catch (e) {
    console.error("Cleanup Failed:", e);
}
